// import dependencies
const { Mongoose } = require('./connection')
const mongoose = require('./connection')

// import user model for populate
const User = require('./user')

// destructure the schema and model constructors from mongoose
const { Schema, model } = mongoose

const favMemeSchema = new Schema(
	{
		ID: { type: Number, required: true },
		bottomText: { type: String, required: false },
		topText: {type: String, required: false},
        image: { type: String, required: true },
		name: { type: String, required: true },
		rank: {type: Number, required: false},
		tags: {type: String, required: false},
		owner: {
			type: Schema.Types.ObjectID,
			ref: 'User',
		}
	},
	{ timestamps: true }
)

const FavMeme = model('FavMeme', favMemeSchema)

/////////////////////////////////
// Export our Model
/////////////////////////////////
module.exports = FavMeme


// //comment: {
// 	memeApiId: (from api)
// 	body: Stringauthor: User Id ref
// }

// //favedMeme: {
// 	_id: generated by Mongo
// 	memeApiId: from API
// 	owner: User ref
// 	comments:[comments]
// //}
